camera_streamer:
  ros__parameters:
    defaults:
      width: 640
      #height: 480
      framerate: 10
      mime: image/jpeg

    # profiles:
    #   snail:
    #     width: 320
    #     height: 240
    #     framerate: 7.5
    #   super:
    #     width: 1280
    #     height: 720
    #     framerate: 10

    serial_pipelines:
      # Waveshare
      openaicam_openaicam_2505121128: # need to test again
        mime: image/jpeg
        framerate: 30
        width: 1920
        height: 1080
      webcamvendor_SK_series1_20220325JWGD2093: # need to test again
        mime: video/x-h264 #image/jpeg
        framerate: 30
        width: 1920
        height: 1080

    serial_pipelines:
      anthony-cam:
        pipeline_type: v4l2webrtc
        width: 1280
        height: 720
        framerate: 30
        mime: image/jpeg
        show_clock: true
        video_caps: video/x-vp9